### ISSUE TITLE
winapi is seemly unmaintained may be more wiser to switch to the official windows_sys crate

### ISSUE THREAD

**Issue by ThalusA** [arcnmx/ddc-winapi-rs#4]
Old: https://github.com/retep998/winapi-rs
New: https://github.com/microsoft/windows-rs
Might make a PR for that but for now just for creating this issue for notice. windows_sys crate seems also easier to use.

**Comment by ThalusA** [comment]
I don't really know which branch I should do a pull request on, they all have non matching commits @arcnmx could you please tell me how I can contribute ?

**Comment by ThalusA** [comment]
Here is an example on how to get edid from windows crate:
```rust
use windows::Devices::Enumeration::DeviceInformation;
use windows::Devices::Display::{DisplayMonitor, DisplayMonitorDescriptorKind};

pub fn list() -> Vec<Vec<u8>> {
    let mut edid_list = vec![];
    if let Ok(ref selector) = DisplayMonitor::GetDeviceSelector() {
        if let Ok(Ok(ref devices)) = DeviceInformation::FindAllAsyncAqsFilter(selector).map(|devices| devices.get()) {
            for device_information in devices {
                if let Ok(Ok(ref device)) = DisplayMonitor::FromInterfaceIdAsync(&device_information.Id().unwrap()).map(|device| device.get()) {
                    if let Ok(edid) = device.GetDescriptor(DisplayMonitorDescriptorKind::Edid) {
                        edid_list.push(edid.to_vec())
                    }
                }
            }
        }
    }
    edid_list
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_list() {
        let displays = list();
        println!("{}, {:?}", displays.len(), displays);
        assert_ne!(displays.len(), 0);
    }
}
```
With a Cargo.toml file as followed : 
```toml
[dependencies.windows]
version = "0.44.0"
features = [
    "Devices_Enumeration",
    "Devices_Display",
    "Foundation",
    "Foundation_Collections"
]
```

**Comment by arcnmx** [comment]
While [windows](https://github.com/arcnmx/ddc-winapi-rs/compare/main...windows) is a branch with the port from `winapi` to `windows`, [v0.3.x](https://github.com/arcnmx/ddc-winapi-rs/tree/v0.3.x) is the next develop branch that already builds on top of it - so the next breaking release will include the switch-over.

**Comment by ThalusA** [comment]
Do you know when will it be done ? it would be nice to only have windows ddc api on windows. If you need any help please tell me where I can help and open a pull request.

**Comment by andycodesstuff** [comment]
Hi @arcnmx, Andrea here. I have recently started using your crate for a side project and I would also be interested in helping get the [v0.3.x](https://github.com/arcnmx/ddc-winapi-rs/tree/v0.3.x) branch reach the release stage - may I ask you what is missing (if any)?

**Comment by arcnmx** [comment]
I've put together [the 0.3.0 milestone](https://github.com/arcnmx/ddc-winapi-rs/milestone/1) to show what's missing. I primarily need to finish the [enumeration I've been experimenting with](https://github.com/arcnmx/ddc-winapi-rs/issues/6) and then [release ddc 0.3](https://github.com/arcnmx/ddc-rs/milestone/1).

For the most part testing helps - if you can try the branch out (depend on it and ddc 0.3 via git, or alternatively use [ddc-hi 0.5](https://github.com/arcnmx/ddc-hi-rs/milestone/1)), feedback in any direction can help push it along. I'm primarily using [ddc-hi 0.5](https://github.com/arcnmx/ddc-hi-rs/milestone/1) and [ddcset](https://github.com/arcnmx/ddcset-rs) as a test implementation to validate the new release - but that isn't as necessary if others are using it successfully!

**Comment by arcnmx** [comment]
For easier testing and to remove myself as a bottleneck, the windows branch has been merged into main and released as an alpha.
