### ISSUE TITLE
Crash in release but not debug

### ISSUE THREAD

**Issue by AndreasBackx** [arcnmx/ddc-winapi-rs#7]
When running `ddc_winapi::Monitor::enumerate()` in debug mode, it works as expected. When running in release mode, it immediately crashes the program with exit code `0xc000041d`. This happens on master (618a2908bb6e5779753c5cdb377653b8e1dba75b) as well.

This is on Rust 1.78.0, Windows 11.

Not sure what else to say, let me know if there's any more information I can provide.

**Comment by cr1901** [comment]
Apply the following patch to `v0.2.x` branch:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 8008050..beaed02 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -242,14 +242,14 @@ pub fn get_physical_monitors_from_hmonitor(monitor: HMONITOR) -> io::Result<Vec<
 /// Enumerates all `HMONITOR`s using the `EnumDisplayMonitors` WinAPI call.
 pub fn enumerate_monitors() -> io::Result<Vec<HMONITOR>> {
     unsafe extern "system" fn callback(monitor: HMONITOR, _hdc_monitor: HDC, _lprc: LPRECT, userdata: LPARAM) -> BOOL {
-        let monitors: &mut Vec<HMONITOR> = mem::transmute(userdata);
+        let monitors: &mut Vec<HMONITOR> = unsafe { &mut *(userdata as *mut Vec<HMONITOR>) };
         monitors.push(monitor);
         TRUE
     }
 
     let mut monitors = Vec::<HMONITOR>::new();
     if unsafe {
-        let userdata = &mut monitors as *mut _;
+        let userdata = ptr::addr_of_mut!(monitors);
         winapi::um::winuser::EnumDisplayMonitors(ptr::null_mut(), ptr::null(), Some(callback), userdata as _)
     } != TRUE {
         Err(io::Error::last_os_error())
```

It seems the callback becomes an (almost<sup>1</sup>) insta-`ud2` on x64 if the `transmute` from `LPARAM`/`isize` to `&mut Vec<HMONITOR>` is kept. Not clear to me whether it's UB to `transmute` from `isize` directly to pointer, but I was at least able to get rid of a `transmute` anyway :D.

## Footnores

1. If I do a `println`, `rustc` is nice enough to wait until that's over to do the `ud2`. Additionally, replacing `monitors.push` with something like `monitors.clear` doesn't trigger the `ud2` codegen either.

**Comment by AndreasBackx** [comment]
Thank you for the patch! I'm currently on holiday without a Windows machine at hand. I'll get back to you when I'm back home. :)

**Comment by arcnmx** [comment]
Should be addressed by #8 in 0.2.2, can anyone else confirm?

**Comment by fenhl** [comment]
Yes, I can confirm this fixes the issue.

**Comment by AndreasBackx** [comment]
Apologies for the late reply. Can also confirm that 0.2.2 fixes it.
